### ISSUE TITLE
Trackpad scrolling is overly sensitive

### ISSUE THREAD

**Issue by vorg** [dariomanesku/cmftStudio#2]
OSX 10.10.3,rMBP

Slide by 1cm and the sphere goes beyond the screen.

**Comment by dariomanesku** [comment]
Magic mouse, apple trackpad? I have a Logitech MX518 and I am getting by just fine.

[This](https://github.com/dariomanesku/bgfx/blob/c5943ded1208575126c66a67b872e7c2de8aa55a/examples/common/entry/entry_osx.mm#L299) is where the input is captured on OSX and [here](https://github.com/dariomanesku/cmftStudio/blob/57c01b62240910fc3c16a8ac1cbb573ac9e5e20b/src/cmftstudio_cpp.h#L487) is the scroll logic (happens on all platforms). Not sure what to do about it since I haven't seen the problem.

A friend of mine is using OSX with Apple peripherals and I'll check on first occasion how it behaves on his machine.

**Comment by dariomanesku** [comment]
I tried cmftStudio on `Apple Magic Mouse` and `Apple Magic Trackpad` and the scroll works ok, it was not super-sensitive. Could it be that you have different system settings?

The implementation looks fine and it is quite consistent across operative systems. I'll leave it as is for now.
